#define _GNU_SOURCE
#include "vpk.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <dirent.h>
#include <errno.h>

// ─────────────────────────────────────────────
//  Internal helpers
// ─────────────────────────────────────────────

static int dir_exists(const char *path) {
    struct stat st;
    return stat(path, &st) == 0 && S_ISDIR(st.st_mode);
}

static int file_exists(const char *path) {
    struct stat st;
    return stat(path, &st) == 0 && S_ISREG(st.st_mode);
}

static int mkdir_p(const char *path) {
    char tmp[512];
    strncpy(tmp, path, sizeof(tmp)-1);
    for (char *p = tmp+1; *p; p++) {
        if (*p == '/') {
            *p = '\0';
            mkdir(tmp, 0755);
            *p = '/';
        }
    }
    return mkdir(tmp, 0755) == 0 || errno == EEXIST ? 0 : -1;
}

static void trim(char *s) {
    // trim leading whitespace
    int i = 0;
    while (s[i]==' '||s[i]=='\t'||s[i]=='\r'||s[i]=='\n') i++;
    if (i) memmove(s, s+i, strlen(s)-i+1);
    // trim trailing
    int len = (int)strlen(s);
    while (len>0 && (s[len-1]==' '||s[len-1]=='\t'||s[len-1]=='\r'||s[len-1]=='\n'))
        s[--len] = '\0';
}

// ─────────────────────────────────────────────
//  Manifest read/write  (simple key=value format)
//
//  taipan.pkg format:
//  ─────────────────
//  name        = mypackage
//  version     = 1.0.0
//  description = Does something cool
//  author      = Dev Name
//  license     = MIT
//  entry       = src/main.tp
//
//  [deps]
//  tensor.linalg = 2.1.0
//  std.http      = *
//
//  [dev-deps]
//  test.runner   = 1.0.0
// ─────────────────────────────────────────────

int vpk_manifest_read(const char *path, VpkManifest *m) {
    memset(m, 0, sizeof(VpkManifest));
    FILE *f = fopen(path, "r");
    if (!f) { fprintf(stderr, "vpk: cannot read '%s'\n", path); return -1; }

    char line[512];
    int section = 0; // 0=top, 1=deps, 2=dev-deps

    while (fgets(line, sizeof(line), f)) {
        trim(line);
        if (!line[0] || line[0]=='#') continue;

        if (!strcmp(line, "[deps]"))     { section=1; continue; }
        if (!strcmp(line, "[dev-deps]")) { section=2; continue; }

        // find '=' separator
        char *eq = strchr(line, '=');
        if (!eq) continue;
        *eq = '\0';
        char *key = line; trim(key);
        char *val = eq+1; trim(val);

        if (section == 0) {
            if      (!strcmp(key,"name"))        strncpy(m->name,        val, VPK_MAX_NAME-1);
            else if (!strcmp(key,"version"))     strncpy(m->version,     val, VPK_MAX_VERSION-1);
            else if (!strcmp(key,"description")) strncpy(m->description, val, 255);
            else if (!strcmp(key,"author"))      strncpy(m->author,      val, 127);
            else if (!strcmp(key,"license"))     strncpy(m->license,     val, 31);
            else if (!strcmp(key,"entry"))       strncpy(m->entry,       val, 255);
        } else if (section == 1 && m->dep_count < VPK_MAX_DEPS) {
            strncpy(m->deps[m->dep_count].name,    key, VPK_MAX_NAME-1);
            strncpy(m->deps[m->dep_count].version, val, VPK_MAX_VERSION-1);
            m->dep_count++;
        } else if (section == 2 && m->dev_dep_count < VPK_MAX_DEPS) {
            strncpy(m->dev_deps[m->dev_dep_count].name,    key, VPK_MAX_NAME-1);
            strncpy(m->dev_deps[m->dev_dep_count].version, val, VPK_MAX_VERSION-1);
            m->dev_dep_count++;
        }
    }
    fclose(f);
    return 0;
}

int vpk_manifest_write(const char *path, const VpkManifest *m) {
    FILE *f = fopen(path, "w");
    if (!f) { fprintf(stderr, "vpk: cannot write '%s'\n", path); return -1; }

    fprintf(f, "# Taipan Package Manifest\n");
    fprintf(f, "# Generated by VPK %s\n\n", VPK_VERSION);
    fprintf(f, "name        = %s\n", m->name);
    fprintf(f, "version     = %s\n", m->version);
    fprintf(f, "description = %s\n", m->description);
    fprintf(f, "author      = %s\n", m->author);
    fprintf(f, "license     = %s\n", m->license);
    fprintf(f, "entry       = %s\n", m->entry[0] ? m->entry : "src/main.tp");

    if (m->dep_count > 0) {
        fprintf(f, "\n[deps]\n");
        for (int i = 0; i < m->dep_count; i++)
            fprintf(f, "%-24s = %s\n", m->deps[i].name, m->deps[i].version);
    }
    if (m->dev_dep_count > 0) {
        fprintf(f, "\n[dev-deps]\n");
        for (int i = 0; i < m->dev_dep_count; i++)
            fprintf(f, "%-24s = %s\n", m->dev_deps[i].name, m->dev_deps[i].version);
    }
    fclose(f);
    return 0;
}

void vpk_manifest_print(const VpkManifest *m) {
    printf("  Name        : %s\n", m->name);
    printf("  Version     : %s\n", m->version);
    printf("  Description : %s\n", m->description);
    printf("  Author      : %s\n", m->author);
    printf("  License     : %s\n", m->license);
    printf("  Entry       : %s\n", m->entry);
    if (m->dep_count > 0) {
        printf("  Dependencies (%d):\n", m->dep_count);
        for (int i = 0; i < m->dep_count; i++)
            printf("    %-24s %s\n", m->deps[i].name, m->deps[i].version);
    }
    if (m->dev_dep_count > 0) {
        printf("  Dev Dependencies (%d):\n", m->dev_dep_count);
        for (int i = 0; i < m->dev_dep_count; i++)
            printf("    %-24s %s\n", m->dev_deps[i].name, m->dev_deps[i].version);
    }
}

// ─────────────────────────────────────────────
//  Lockfile  (.vpk/lock.pkg)
//  name=version|checksum|path  one per line
// ─────────────────────────────────────────────

int vpk_lock_read(const char *path, VpkInstalled *pkgs, int *count) {
    *count = 0;
    FILE *f = fopen(path, "r");
    if (!f) return 0; // lockfile may not exist yet

    char line[768];
    while (fgets(line, sizeof(line), f) && *count < VPK_MAX_DEPS) {
        trim(line);
        if (!line[0] || line[0]=='#') continue;
        VpkInstalled *p = &pkgs[*count];
        // format: name|version|checksum|path
        char *tok = strtok(line, "|");
        if (!tok) continue; strncpy(p->name,         tok, VPK_MAX_NAME-1);
        tok = strtok(NULL, "|");
        if (!tok) continue; strncpy(p->version,      tok, VPK_MAX_VERSION-1);
        tok = strtok(NULL, "|");
        if (!tok) continue; strncpy(p->checksum,     tok, 64);
        tok = strtok(NULL, "|");
        if (tok)            strncpy(p->install_path, tok, 511);
        (*count)++;
    }
    fclose(f);
    return 0;
}

int vpk_lock_write(const char *path, const VpkInstalled *pkgs, int count) {
    mkdir_p(".vpk");
    FILE *f = fopen(path, "w");
    if (!f) { fprintf(stderr, "vpk: cannot write lockfile\n"); return -1; }
    fprintf(f, "# VPK lockfile — do not edit manually\n");
    for (int i = 0; i < count; i++)
        fprintf(f, "%s|%s|%s|%s\n",
            pkgs[i].name, pkgs[i].version,
            pkgs[i].checksum, pkgs[i].install_path);
    fclose(f);
    return 0;
}

// ─────────────────────────────────────────────
//  ensure .vpk/ directory structure exists
// ─────────────────────────────────────────────

int vpk_ensure_dirs(void) {
    mkdir_p(".vpk");
    mkdir_p(VPK_PKG_DIR);
    return 0;
}

// ─────────────────────────────────────────────
//  vpk init
// ─────────────────────────────────────────────

int vpk_init(const char *dir) {
    char manifest_path[512];
    snprintf(manifest_path, sizeof(manifest_path), "%s/%s",
             dir ? dir : ".", VPK_MANIFEST);

    if (file_exists(manifest_path)) {
        fprintf(stderr, "vpk: %s already exists\n", VPK_MANIFEST);
        return 1;
    }

    // Prompt for package details
    VpkManifest m;
    memset(&m, 0, sizeof(m));

    char cwd[256] = {0};
    if (getcwd(cwd, sizeof(cwd))) {
        // use last component of cwd as default name
        char *base = strrchr(cwd, '/');
        if (base) strncpy(m.name, base+1, VPK_MAX_NAME-1);
        else      strncpy(m.name, cwd,    VPK_MAX_NAME-1);
    } else {
        strncpy(m.name, "my-package", VPK_MAX_NAME-1);
    }

    strncpy(m.version,     "0.1.0",           VPK_MAX_VERSION-1);
    strncpy(m.description, "A Taipan package", 255);
    strncpy(m.author,      "",                 127);
    strncpy(m.license,     "MIT",              31);
    strncpy(m.entry,       "src/main.tp",      255);

    // Interactive prompts
    char buf[256];
    printf("VPK Init — creating %s\n\n", VPK_MANIFEST);

    printf("Package name [%s]: ", m.name);
    fflush(stdout);
    if (fgets(buf, sizeof(buf), stdin)) {
        trim(buf);
        if (buf[0]) strncpy(m.name, buf, VPK_MAX_NAME-1);
    }
    printf("Version [%s]: ", m.version);
    fflush(stdout);
    if (fgets(buf, sizeof(buf), stdin)) {
        trim(buf);
        if (buf[0]) strncpy(m.version, buf, VPK_MAX_VERSION-1);
    }
    printf("Description: ");
    fflush(stdout);
    if (fgets(buf, sizeof(buf), stdin)) {
        trim(buf);
        if (buf[0]) strncpy(m.description, buf, 255);
    }
    printf("Author: ");
    fflush(stdout);
    if (fgets(buf, sizeof(buf), stdin)) {
        trim(buf);
        if (buf[0]) strncpy(m.author, buf, 127);
    }
    printf("License [%s]: ", m.license);
    fflush(stdout);
    if (fgets(buf, sizeof(buf), stdin)) {
        trim(buf);
        if (buf[0]) strncpy(m.license, buf, 31);
    }
    printf("Entry file [%s]: ", m.entry);
    fflush(stdout);
    if (fgets(buf, sizeof(buf), stdin)) {
        trim(buf);
        if (buf[0]) strncpy(m.entry, buf, 255);
    }

    if (vpk_manifest_write(manifest_path, &m) != 0) return 1;

    // Create src/ directory
    mkdir_p("src");
    vpk_ensure_dirs();

    // Create src/main.tp stub if it doesn't exist
    char main_path[512];
    snprintf(main_path, sizeof(main_path), "%s", m.entry);
    if (!file_exists(main_path)) {
        // ensure parent dir
        char parent[512];
        strncpy(parent, main_path, sizeof(parent)-1);
        char *sl = strrchr(parent, '/');
        if (sl) { *sl='\0'; mkdir_p(parent); }

        FILE *mf = fopen(main_path, "w");
        if (mf) {
            fprintf(mf, "use std.io\n\nfn main() {\n    println(\"Hello from %s!\")\n}\n", m.name);
            fclose(mf);
            printf("\nCreated %s\n", main_path);
        }
    }

    printf("\n✅  Initialized package '%s' v%s\n", m.name, m.version);
    printf("    %s created\n", VPK_MANIFEST);
    printf("\nNext steps:\n");
    printf("  venom %s --link    # build\n", m.entry);
    printf("  vpk install <pkg>  # add a dependency\n");
    return 0;
}

// ─────────────────────────────────────────────
//  vpk install
// ─────────────────────────────────────────────

int vpk_install(const char *pkg_name, const char *version) {
    if (!pkg_name) { fprintf(stderr, "vpk: install requires a package name\n"); return 1; }
    const char *ver = version ? version : "*";

    printf("vpk: installing %s@%s ...\n", pkg_name, ver);

    // Check if manifest exists; if so add dependency
    VpkManifest m;
    int has_manifest = (vpk_manifest_read(VPK_MANIFEST, &m) == 0);

    // Check if already installed
    VpkInstalled lock[VPK_MAX_DEPS];
    int lock_count = 0;
    vpk_lock_read(VPK_LOCKFILE, lock, &lock_count);

    for (int i = 0; i < lock_count; i++) {
        if (!strcmp(lock[i].name, pkg_name)) {
            printf("vpk: %s@%s already installed\n", pkg_name, lock[i].version);
            return 0;
        }
    }

    vpk_ensure_dirs();

    // Simulate download (in real VPK this would fetch from registry)
    char pkg_dir[512];
    snprintf(pkg_dir, sizeof(pkg_dir), "%s/%s", VPK_PKG_DIR, pkg_name);
    mkdir_p(pkg_dir);

    // Create a placeholder package stub
    char stub_path[512];
    snprintf(stub_path, sizeof(stub_path), "%s/lib.tp", pkg_dir);
    FILE *sf = fopen(stub_path, "w");
    if (sf) {
        fprintf(sf, "// Package: %s v%s\n// Installed by VPK\nuse std.io\n", pkg_name, ver);
        fclose(sf);
    }

    // Record in lockfile
    VpkInstalled *p = &lock[lock_count++];
    strncpy(p->name,         pkg_name, VPK_MAX_NAME-1);
    strncpy(p->version,      strcmp(ver,"*")==0 ? "latest" : ver, VPK_MAX_VERSION-1);
    strncpy(p->checksum,     "0000000000000000000000000000000000000000000000000000000000000000", 64);
    strncpy(p->install_path, pkg_dir,  511);
    vpk_lock_write(VPK_LOCKFILE, lock, lock_count);

    // Add to manifest deps if manifest exists
    if (has_manifest && m.dep_count < VPK_MAX_DEPS) {
        // check not already in deps
        int found = 0;
        for (int i = 0; i < m.dep_count; i++)
            if (!strcmp(m.deps[i].name, pkg_name)) { found=1; break; }
        if (!found) {
            strncpy(m.deps[m.dep_count].name,    pkg_name, VPK_MAX_NAME-1);
            strncpy(m.deps[m.dep_count].version, ver,      VPK_MAX_VERSION-1);
            m.dep_count++;
            vpk_manifest_write(VPK_MANIFEST, &m);
            printf("vpk: added %s to %s\n", pkg_name, VPK_MANIFEST);
        }
    }

    printf("✅  Installed %s@%s → %s\n", pkg_name, p->version, pkg_dir);
    return 0;
}

// ─────────────────────────────────────────────
//  vpk remove
// ─────────────────────────────────────────────

int vpk_remove(const char *pkg_name) {
    if (!pkg_name) { fprintf(stderr, "vpk: remove requires a package name\n"); return 1; }

    VpkInstalled lock[VPK_MAX_DEPS];
    int lock_count = 0;
    vpk_lock_read(VPK_LOCKFILE, lock, &lock_count);

    int found = -1;
    for (int i = 0; i < lock_count; i++)
        if (!strcmp(lock[i].name, pkg_name)) { found = i; break; }

    if (found < 0) {
        fprintf(stderr, "vpk: %s is not installed\n", pkg_name);
        return 1;
    }

    // Remove package directory
    char cmd[600];
    snprintf(cmd, sizeof(cmd), "rm -rf %s", lock[found].install_path);
    system(cmd);

    // Remove from lockfile
    for (int i = found; i < lock_count-1; i++)
        lock[i] = lock[i+1];
    lock_count--;
    vpk_lock_write(VPK_LOCKFILE, lock, lock_count);

    // Remove from manifest
    VpkManifest m;
    if (vpk_manifest_read(VPK_MANIFEST, &m) == 0) {
        for (int i = 0; i < m.dep_count; i++) {
            if (!strcmp(m.deps[i].name, pkg_name)) {
                for (int j = i; j < m.dep_count-1; j++) m.deps[j] = m.deps[j+1];
                m.dep_count--;
                vpk_manifest_write(VPK_MANIFEST, &m);
                break;
            }
        }
    }

    printf("✅  Removed %s\n", pkg_name);
    return 0;
}

// ─────────────────────────────────────────────
//  vpk list
// ─────────────────────────────────────────────

int vpk_list(void) {
    VpkInstalled lock[VPK_MAX_DEPS];
    int count = 0;
    vpk_lock_read(VPK_LOCKFILE, lock, &count);

    if (count == 0) {
        printf("vpk: no packages installed\n");
        printf("     run 'vpk install <package>' to add one\n");
        return 0;
    }

    printf("Installed packages (%d):\n", count);
    printf("  %-32s %-12s %s\n", "Package", "Version", "Path");
    printf("  %-32s %-12s %s\n", "───────────────────────────────", "───────────", "──────────────");
    for (int i = 0; i < count; i++)
        printf("  %-32s %-12s %s\n",
               lock[i].name, lock[i].version, lock[i].install_path);
    return 0;
}

// ─────────────────────────────────────────────
//  vpk search  (stub — would query registry)
// ─────────────────────────────────────────────

int vpk_search(const char *query) {
    printf("Searching registry for '%s'...\n\n", query);

    // Simulated registry results
    typedef struct { const char *name; const char *ver; const char *desc; } Pkg;
    Pkg catalog[] = {
        {"tensor.linalg",  "2.1.0", "Linear algebra for Taipan tensors"},
        {"tensor.nn",      "1.0.3", "Neural network layers and ops"},
        {"std.http",       "1.2.0", "HTTP client and server"},
        {"std.json",       "1.1.0", "JSON parse and serialize"},
        {"std.crypto",     "0.9.0", "Cryptographic primitives"},
        {"game.physics",   "0.5.0", "2D/3D physics engine"},
        {"game.render",    "0.4.0", "Rendering pipeline"},
        {"util.csv",       "1.0.0", "CSV parsing utilities"},
        {"util.regex",     "0.8.0", "Regular expressions"},
        {"sys.kernel",     "0.2.0", "Low-level kernel interface"},
    };

    int found = 0;
    printf("  %-28s %-8s %s\n", "Package", "Version", "Description");
    printf("  %-28s %-8s %s\n", "───────────────────────────", "───────", "──────────────────────────");
    for (int i = 0; i < (int)(sizeof(catalog)/sizeof(catalog[0])); i++) {
        if (!query || strstr(catalog[i].name, query) || strstr(catalog[i].desc, query)) {
            printf("  %-28s %-8s %s\n", catalog[i].name, catalog[i].ver, catalog[i].desc);
            found++;
        }
    }
    if (found == 0) printf("  No packages found for '%s'\n", query);
    else printf("\n%d package(s) found. Run 'vpk install <name>' to install.\n", found);
    return 0;
}

// ─────────────────────────────────────────────
//  vpk info
// ─────────────────────────────────────────────

int vpk_info(const char *pkg_name) {
    if (!pkg_name) {
        // Show current project info
        VpkManifest m;
        if (vpk_manifest_read(VPK_MANIFEST, &m) != 0) {
            fprintf(stderr, "vpk: no %s found. Run 'vpk init'\n", VPK_MANIFEST);
            return 1;
        }
        printf("Package info:\n");
        vpk_manifest_print(&m);
        return 0;
    }

    // Show installed package info
    VpkInstalled lock[VPK_MAX_DEPS];
    int count = 0;
    vpk_lock_read(VPK_LOCKFILE, lock, &count);
    for (int i = 0; i < count; i++) {
        if (!strcmp(lock[i].name, pkg_name)) {
            printf("Package: %s\n", lock[i].name);
            printf("Version: %s\n", lock[i].version);
            printf("Path:    %s\n", lock[i].install_path);
            printf("SHA256:  %s\n", lock[i].checksum);
            return 0;
        }
    }
    fprintf(stderr, "vpk: '%s' is not installed\n", pkg_name);
    return 1;
}

// ─────────────────────────────────────────────
//  vpk update
// ─────────────────────────────────────────────

int vpk_update(void) {
    VpkInstalled lock[VPK_MAX_DEPS];
    int count = 0;
    vpk_lock_read(VPK_LOCKFILE, lock, &count);

    if (count == 0) { printf("vpk: nothing to update\n"); return 0; }

    printf("Checking for updates...\n");
    for (int i = 0; i < count; i++)
        printf("  %-32s %s → (up to date)\n", lock[i].name, lock[i].version);
    printf("\n✅  All packages up to date\n");
    return 0;
}

// ─────────────────────────────────────────────
//  vpk publish  (stub)
// ─────────────────────────────────────────────

int vpk_publish(void) {
    VpkManifest m;
    if (vpk_manifest_read(VPK_MANIFEST, &m) != 0) {
        fprintf(stderr, "vpk: no %s found. Run 'vpk init'\n", VPK_MANIFEST);
        return 1;
    }
    printf("Publishing %s v%s to %s ...\n", m.name, m.version, VPK_REGISTRY_URL);
    printf("\n⚠️  Registry not yet live.\n");
    printf("    Package prepared: %s v%s\n", m.name, m.version);
    printf("    When the registry is ready, this will publish automatically.\n");
    return 0;
}

// ─────────────────────────────────────────────
//  Usage
// ─────────────────────────────────────────────

void vpk_usage(const char *argv0) {
    fprintf(stderr,
        "VPK — Taipan Package Manager v%s\n"
        "Usage: %s <command> [args]\n"
        "\n"
        "Commands:\n"
        "  init                 Create taipan.pkg in current directory\n"
        "  install <pkg>        Install a package\n"
        "  install <pkg>@<ver>  Install a specific version\n"
        "  remove  <pkg>        Remove a package\n"
        "  list                 List installed packages\n"
        "  search  [query]      Search the package registry\n"
        "  update               Update all packages\n"
        "  info    [pkg]        Show package info (current project if no pkg)\n"
        "  publish              Publish current package to registry\n"
        "\n"
        "Examples:\n"
        "  %s init\n"
        "  %s install tensor.linalg\n"
        "  %s install std.http@1.2.0\n"
        "  %s search tensor\n"
        "  %s list\n"
        "  %s remove std.http\n",
        VPK_VERSION, argv0,
        argv0, argv0, argv0, argv0, argv0, argv0
    );
}