; Taipan — LLVM IR (generated by Venom)
target triple = "x86_64-pc-linux-gnu"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i8* @malloc(i32)
declare i8* @__taipan_array_new(i32, i32)
declare void @free(i8*)
declare i32 @__taipan_array_len(i8*)

%struct.Point = type { float, float }

define %struct.Point* @Point__new(float %init.x, float %init.y) {
entry:
  %1 = getelementptr inbounds %struct.Point, %struct.Point* null, i32 1
  %2 = ptrtoint %struct.Point* %1 to i64
  %3 = call i8* @malloc(i64 %2)
  %4 = bitcast i8* %3 to %struct.Point*
  %5 = getelementptr inbounds %struct.Point, %struct.Point* %4, i32 0, i32 0
  store float %init.x, float* %5
  %6 = getelementptr inbounds %struct.Point, %struct.Point* %4, i32 0, i32 1
  store float %init.y, float* %6
  %7 = bitcast %struct.Point* %4 to %struct.Point*
  ret %struct.Point* %7
}

define void @Point__describe(%struct.Point* %self) {
entry:
  %1 = alloca %struct.Point*
  store %struct.Point* %self, %struct.Point** %1
  %2 = getelementptr inbounds [14 x i8], [14 x i8]* @.str.0, i32 0, i32 0
  %3 = call i32 @puts(i8* %2)
  %4 = load %struct.Point*, %struct.Point** %1
  %5 = getelementptr inbounds %struct.Point, %struct.Point* %4, i32 0, i32 0
  %6 = load float, float* %5
  %7 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtf, i32 0, i32 0
  %8 = fpext float %6 to double
  %9 = call i32 (i8*, ...) @printf(i8* %7, double %8)
  %10 = load %struct.Point*, %struct.Point** %1
  %11 = getelementptr inbounds %struct.Point, %struct.Point* %10, i32 0, i32 1
  %12 = load float, float* %11
  %13 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtf, i32 0, i32 0
  %14 = fpext float %12 to double
  %15 = call i32 (i8*, ...) @printf(i8* %13, double %14)
  ret void
}

%struct.Rectangle = type { float, float }

define %struct.Rectangle* @Rectangle__new(float %init.width, float %init.height) {
entry:
  %1 = getelementptr inbounds %struct.Rectangle, %struct.Rectangle* null, i32 1
  %2 = ptrtoint %struct.Rectangle* %1 to i64
  %3 = call i8* @malloc(i64 %2)
  %4 = bitcast i8* %3 to %struct.Rectangle*
  %5 = getelementptr inbounds %struct.Rectangle, %struct.Rectangle* %4, i32 0, i32 0
  store float %init.width, float* %5
  %6 = getelementptr inbounds %struct.Rectangle, %struct.Rectangle* %4, i32 0, i32 1
  store float %init.height, float* %6
  %7 = bitcast %struct.Rectangle* %4 to %struct.Rectangle*
  ret %struct.Rectangle* %7
}

define float @Rectangle__area(%struct.Rectangle* %self) {
entry:
  %1 = alloca %struct.Rectangle*
  store %struct.Rectangle* %self, %struct.Rectangle** %1
  %2 = load %struct.Rectangle*, %struct.Rectangle** %1
  %3 = getelementptr inbounds %struct.Rectangle, %struct.Rectangle* %2, i32 0, i32 0
  %4 = load float, float* %3
  %5 = load %struct.Rectangle*, %struct.Rectangle** %1
  %6 = getelementptr inbounds %struct.Rectangle, %struct.Rectangle* %5, i32 0, i32 1
  %7 = load float, float* %6
  %8 = fmul float %4, %7
  ret float %8
}

define i32 @main() {
entry:
  %9 = call %struct.Point* @Point__new(float 0x4008000000000000, float 0x4010000000000000)
  %10 = alloca %struct.Point*
  store %struct.Point* %9, %struct.Point** %10
  %11 = load %struct.Point*, %struct.Point** %10
  call void @Point__describe(%struct.Point* %11)
  %12 = call %struct.Rectangle* @Rectangle__new(float 0x4024000000000000, float 0x4014000000000000)
  %13 = alloca %struct.Rectangle*
  store %struct.Rectangle* %12, %struct.Rectangle** %13
  %14 = getelementptr inbounds [11 x i8], [11 x i8]* @.str.1, i32 0, i32 0
  %15 = call i32 @puts(i8* %14)
  %16 = load %struct.Rectangle*, %struct.Rectangle** %13
  %17 = getelementptr inbounds %struct.Rectangle, %struct.Rectangle* %16, i32 0, i32 0
  %18 = load float, float* %17
  %19 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtf, i32 0, i32 0
  %20 = fpext float %18 to double
  %21 = call i32 (i8*, ...) @printf(i8* %19, double %20)
  ret i32 0
}


; String constants
@.fmtd = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmtf = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.0 = private unnamed_addr constant [14 x i8] c"Point entity:\00"
@.str.1 = private unnamed_addr constant [11 x i8] c"Rectangle:\00"
