; Taipan — LLVM IR (generated by Venom)
target triple = "x86_64-pc-linux-gnu"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i8* @malloc(i32)
declare i8* @__taipan_array_new(i32, i32)
declare void @free(i8*)
declare i32 @__taipan_array_len(i8*)

%struct.Circle = type { float }

define %struct.Circle* @Circle__new(float %init.radius) {
entry:
  %1 = getelementptr inbounds %struct.Circle, %struct.Circle* null, i32 1
  %2 = ptrtoint %struct.Circle* %1 to i64
  %3 = call i8* @malloc(i64 %2)
  %4 = bitcast i8* %3 to %struct.Circle*
  %5 = getelementptr inbounds %struct.Circle, %struct.Circle* %4, i32 0, i32 0
  store float %init.radius, float* %5
  %6 = bitcast %struct.Circle* %4 to %struct.Circle*
  ret %struct.Circle* %6
}

define float @Circle__area(%struct.Circle* %self) {
entry:
  %1 = alloca %struct.Circle*
  store %struct.Circle* %self, %struct.Circle** %1
  %2 = load %struct.Circle*, %struct.Circle** %1
  %3 = getelementptr inbounds %struct.Circle, %struct.Circle* %2, i32 0, i32 0
  %4 = load float, float* %3
  %5 = load %struct.Circle*, %struct.Circle** %1
  %6 = getelementptr inbounds %struct.Circle, %struct.Circle* %5, i32 0, i32 0
  %7 = load float, float* %6
  %8 = fmul float %4, %7
  %9 = fmul float %8, 0x400921FA00000000
  ret float %9
}

define void @Circle__describe(%struct.Circle* %self) {
entry:
  %1 = alloca %struct.Circle*
  store %struct.Circle* %self, %struct.Circle** %1
  %2 = load %struct.Circle*, %struct.Circle** %1
  %3 = call float @Circle__area(%struct.Circle* %2)
  %4 = alloca float
  store float %3, float* %4
  %5 = getelementptr inbounds [8 x i8], [8 x i8]* @.str.0, i32 0, i32 0
  %6 = call i32 @puts(i8* %5)
  %7 = load %struct.Circle*, %struct.Circle** %1
  %8 = getelementptr inbounds %struct.Circle, %struct.Circle* %7, i32 0, i32 0
  %9 = load float, float* %8
  %10 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtf, i32 0, i32 0
  %11 = fpext float %9 to double
  %12 = call i32 (i8*, ...) @printf(i8* %10, double %11)
  %13 = getelementptr inbounds [6 x i8], [6 x i8]* @.str.1, i32 0, i32 0
  %14 = call i32 @puts(i8* %13)
  %15 = load float, float* %4
  %16 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtf, i32 0, i32 0
  %17 = fpext float %15 to double
  %18 = call i32 (i8*, ...) @printf(i8* %16, double %17)
  ret void
}

define i32 @main() {
entry:
  %19 = call %struct.Circle* @Circle__new(float 0x4014000000000000)
  %20 = alloca %struct.Circle*
  store %struct.Circle* %19, %struct.Circle** %20
  %21 = load %struct.Circle*, %struct.Circle** %20
  call void @Circle__describe(%struct.Circle* %21)
  %22 = load %struct.Circle*, %struct.Circle** %20
  %23 = call float @Circle__area(%struct.Circle* %22)
  %24 = alloca float
  store float %23, float* %24
  %25 = getelementptr inbounds [18 x i8], [18 x i8]* @.str.2, i32 0, i32 0
  %26 = call i32 @puts(i8* %25)
  %27 = load float, float* %24
  %28 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtf, i32 0, i32 0
  %29 = fpext float %27 to double
  %30 = call i32 (i8*, ...) @printf(i8* %28, double %29)
  %31 = getelementptr inbounds float, float* null, i32 1
  %32 = ptrtoint float* %31 to i32
  %33 = call i8* @__taipan_array_new(i32 4, i32 %32)
  %34 = bitcast i8* %33 to float*
  %35 = getelementptr inbounds float, float* %34, i32 0
  store float 0x3FF8000000000000, float* %35
  %36 = getelementptr inbounds float, float* %34, i32 1
  store float 0x4004000000000000, float* %36
  %37 = getelementptr inbounds float, float* %34, i32 2
  store float 0x400C000000000000, float* %37
  %38 = getelementptr inbounds float, float* %34, i32 3
  store float 0x4012000000000000, float* %38
  %39 = alloca float*
  store float* %34, float** %39
  %40 = alloca float
  store float 0x0000000000000000, float* %40
  %41 = alloca i32
  store i32 0, i32* %41
  %42 = load float*, float** %39
  %43 = alloca float
  %44 = bitcast float* %42 to i8*
  %45 = call i32 @__taipan_array_len(i8* %44)
  br label %foriter.cond.0
foriter.cond.0:
  %46 = load i32, i32* %41
  %47 = icmp slt i32 %46, %45
  br i1 %47, label %foriter.body.0, label %foriter.end.0
foriter.body.0:
  %48 = getelementptr inbounds float, float* %42, i32 %46
  %49 = load float, float* %48
  store float %49, float* %43
  %50 = load float, float* %40
  %51 = load float, float* %43
  %52 = fadd float %50, %51
  store float %52, float* %40
  %53 = load i32, i32* %41
  %54 = add i32 %53, 1
  store i32 %54, i32* %41
  br label %foriter.cond.0
foriter.end.0:
  %55 = getelementptr inbounds [11 x i8], [11 x i8]* @.str.3, i32 0, i32 0
  %56 = call i32 @puts(i8* %55)
  %57 = load float, float* %40
  %58 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtf, i32 0, i32 0
  %59 = fpext float %57 to double
  %60 = call i32 (i8*, ...) @printf(i8* %58, double %59)
  ret i32 0
}


; String constants
@.fmtd = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmtf = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.0 = private unnamed_addr constant [8 x i8] c"radius:\00"
@.str.1 = private unnamed_addr constant [6 x i8] c"area:\00"
@.str.2 = private unnamed_addr constant [18 x i8] c"direct area call:\00"
@.str.3 = private unnamed_addr constant [11 x i8] c"float sum:\00"
