; Taipan — LLVM IR (generated by Venom)
target triple = "x86_64-pc-linux-gnu"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i8* @malloc(i32)
declare i8* @__taipan_array_new(i32, i32)
declare void @free(i8*)
declare i32 @__taipan_array_len(i8*)
declare i32 @__taipan_str_len(i8*)
declare i8* @__taipan_str_concat(i8*, i8*)
declare i32 @__taipan_str_eq(i8*, i8*)
declare i8* @__taipan_str_slice(i8*, i32, i32)

define i32 @main() {
entry:
  %0 = getelementptr inbounds [15 x i8], [15 x i8]* @.str.0, i32 0, i32 0
  %1 = call i32 @puts(i8* %0)
  ret i32 0
}


; String constants
@.fmtd = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmtf = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.0 = private unnamed_addr constant [15 x i8] c"Hello, Taipan!\00"
