; Taipan — LLVM IR (generated by Venom)
target triple = "x86_64-pc-linux-gnu"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i8* @malloc(i32)
declare i8* @__taipan_array_new(i32, i32)
declare void @free(i8*)
declare i32 @__taipan_array_len(i8*)
declare i32 @__taipan_str_len(i8*)
declare i8* @__taipan_str_concat(i8*, i8*)
declare i32 @__taipan_str_eq(i8*, i8*)
declare i8* @__taipan_str_slice(i8*, i32, i32)
declare float @__taipan_sqrt(float)
declare float @__taipan_pow(float, float)
declare float @__taipan_abs_f(float)
declare float @__taipan_floor(float)
declare float @__taipan_ceil(float)
declare float @__taipan_sin(float)
declare float @__taipan_cos(float)
declare float @__taipan_tan(float)
declare float @__taipan_log(float)
declare float @__taipan_log2(float)
declare i32 @__taipan_abs_i(i32)
declare i32 @__taipan_min_i(i32, i32)
declare i32 @__taipan_max_i(i32, i32)
declare float @__taipan_min_f(float, float)
declare float @__taipan_max_f(float, float)

define i32 @main() {
entry:
  %0 = getelementptr inbounds i32, i32* null, i32 1
  %1 = ptrtoint i32* %0 to i32
  %2 = call i8* @__taipan_array_new(i32 5, i32 %1)
  %3 = bitcast i8* %2 to i32*
  %4 = getelementptr inbounds i32, i32* %3, i32 0
  store i32 10, i32* %4
  %5 = getelementptr inbounds i32, i32* %3, i32 1
  store i32 20, i32* %5
  %6 = getelementptr inbounds i32, i32* %3, i32 2
  store i32 30, i32* %6
  %7 = getelementptr inbounds i32, i32* %3, i32 3
  store i32 40, i32* %7
  %8 = getelementptr inbounds i32, i32* %3, i32 4
  store i32 50, i32* %8
  %9 = alloca i32*
  store i32* %3, i32** %9
  %10 = alloca i32
  store i32 0, i32* %10
  %11 = alloca i32
  store i32 0, i32* %11
  %12 = load i32*, i32** %9
  %13 = alloca i32
  %14 = bitcast i32* %12 to i8*
  %15 = call i32 @__taipan_array_len(i8* %14)
  br label %foriter.cond.0
foriter.cond.0:
  %16 = load i32, i32* %11
  %17 = icmp slt i32 %16, %15
  br i1 %17, label %foriter.body.0, label %foriter.end.0
foriter.body.0:
  %18 = getelementptr inbounds i32, i32* %12, i32 %16
  %19 = load i32, i32* %18
  store i32 %19, i32* %13
  %20 = load i32, i32* %10
  %21 = load i32, i32* %13
  %22 = add i32 %20, %21
  store i32 %22, i32* %10
  %23 = load i32, i32* %11
  %24 = add i32 %23, 1
  store i32 %24, i32* %11
  br label %foriter.cond.0
foriter.end.0:
  %25 = getelementptr inbounds [5 x i8], [5 x i8]* @.str.0, i32 0, i32 0
  %26 = call i32 @puts(i8* %25)
  %27 = load i32, i32* %10
  %28 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtd, i32 0, i32 0
  %29 = call i32 (i8*, ...) @printf(i8* %28, i32 %27)
  %30 = alloca i32
  store i32 0, i32* %30
  %31 = load i32*, i32** %9
  %32 = alloca i32
  %33 = bitcast i32* %31 to i8*
  %34 = call i32 @__taipan_array_len(i8* %33)
  br label %foriter.cond.1
foriter.cond.1:
  %35 = load i32, i32* %30
  %36 = icmp slt i32 %35, %34
  br i1 %36, label %foriter.body.1, label %foriter.end.1
foriter.body.1:
  %37 = getelementptr inbounds i32, i32* %31, i32 %35
  %38 = load i32, i32* %37
  store i32 %38, i32* %32
  %39 = load i32, i32* %32
  %40 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtd, i32 0, i32 0
  %41 = call i32 (i8*, ...) @printf(i8* %40, i32 %39)
  %42 = load i32, i32* %30
  %43 = add i32 %42, 1
  store i32 %43, i32* %30
  br label %foriter.cond.1
foriter.end.1:
  ret i32 0
}


; String constants
@.fmtd = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmtf = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.fmtd_no_nl = private unnamed_addr constant [3 x i8] c"%d\00"
@.fmtf_no_nl = private unnamed_addr constant [3 x i8] c"%f\00"
@.fmts = private unnamed_addr constant [3 x i8] c"%s\00"
@.str.0 = private unnamed_addr constant [5 x i8] c"Sum:\00"
