; Taipan — LLVM IR (generated by Venom)
target triple = "x86_64-pc-linux-gnu"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i8* @malloc(i32)
declare i8* @__taipan_array_new(i32, i32)
declare void @free(i8*)
declare i32 @__taipan_array_len(i8*)

%struct.Vec2 = type { float, float }

define %struct.Vec2* @Vec2__new(float %init.x, float %init.y) {
entry:
  %1 = getelementptr inbounds %struct.Vec2, %struct.Vec2* null, i32 1
  %2 = ptrtoint %struct.Vec2* %1 to i64
  %3 = call i8* @malloc(i64 %2)
  %4 = bitcast i8* %3 to %struct.Vec2*
  %5 = getelementptr inbounds %struct.Vec2, %struct.Vec2* %4, i32 0, i32 0
  store float %init.x, float* %5
  %6 = getelementptr inbounds %struct.Vec2, %struct.Vec2* %4, i32 0, i32 1
  store float %init.y, float* %6
  %7 = bitcast %struct.Vec2* %4 to %struct.Vec2*
  ret %struct.Vec2* %7
}

define void @Vec2__scale(%struct.Vec2* %self, float %param.factor) {
entry:
  %1 = alloca %struct.Vec2*
  store %struct.Vec2* %self, %struct.Vec2** %1
  %2 = alloca float
  store float %param.factor, float* %2
  %3 = load %struct.Vec2*, %struct.Vec2** %1
  %4 = getelementptr inbounds %struct.Vec2, %struct.Vec2* %3, i32 0, i32 0
  %5 = load float, float* %4
  %6 = load float, float* %2
  %7 = fmul float %5, %6
  %8 = load %struct.Vec2*, %struct.Vec2** %1
  %9 = getelementptr inbounds %struct.Vec2, %struct.Vec2* %8, i32 0, i32 0
  store float %7, float* %9
  %10 = load %struct.Vec2*, %struct.Vec2** %1
  %11 = getelementptr inbounds %struct.Vec2, %struct.Vec2* %10, i32 0, i32 1
  %12 = load float, float* %11
  %13 = load float, float* %2
  %14 = fmul float %12, %13
  %15 = load %struct.Vec2*, %struct.Vec2** %1
  %16 = getelementptr inbounds %struct.Vec2, %struct.Vec2* %15, i32 0, i32 1
  store float %14, float* %16
  ret void
}

define void @Vec2__translate(%struct.Vec2* %self, float %param.dx, float %param.dy) {
entry:
  %1 = alloca %struct.Vec2*
  store %struct.Vec2* %self, %struct.Vec2** %1
  %2 = alloca float
  store float %param.dx, float* %2
  %3 = alloca float
  store float %param.dy, float* %3
  %4 = load float, float* %2
  %5 = load %struct.Vec2*, %struct.Vec2** %1
  %6 = getelementptr inbounds %struct.Vec2, %struct.Vec2* %5, i32 0, i32 0
  %7 = load float, float* %6
  %8 = fadd float %7, %4
  store float %8, float* %6
  %9 = load float, float* %3
  %10 = load %struct.Vec2*, %struct.Vec2** %1
  %11 = getelementptr inbounds %struct.Vec2, %struct.Vec2* %10, i32 0, i32 1
  %12 = load float, float* %11
  %13 = fadd float %12, %9
  store float %13, float* %11
  ret void
}

define void @Vec2__print_vec(%struct.Vec2* %self) {
entry:
  %1 = alloca %struct.Vec2*
  store %struct.Vec2* %self, %struct.Vec2** %1
  %2 = getelementptr inbounds [3 x i8], [3 x i8]* @.str.0, i32 0, i32 0
  %3 = call i32 @puts(i8* %2)
  %4 = load %struct.Vec2*, %struct.Vec2** %1
  %5 = getelementptr inbounds %struct.Vec2, %struct.Vec2* %4, i32 0, i32 0
  %6 = load float, float* %5
  %7 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtf, i32 0, i32 0
  %8 = fpext float %6 to double
  %9 = call i32 (i8*, ...) @printf(i8* %7, double %8)
  %10 = getelementptr inbounds [3 x i8], [3 x i8]* @.str.1, i32 0, i32 0
  %11 = call i32 @puts(i8* %10)
  %12 = load %struct.Vec2*, %struct.Vec2** %1
  %13 = getelementptr inbounds %struct.Vec2, %struct.Vec2* %12, i32 0, i32 1
  %14 = load float, float* %13
  %15 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmtf, i32 0, i32 0
  %16 = fpext float %14 to double
  %17 = call i32 (i8*, ...) @printf(i8* %15, double %16)
  ret void
}

define i32 @main() {
entry:
  %18 = call %struct.Vec2* @Vec2__new(float 0x4000000000000000, float 0x4008000000000000)
  %19 = alloca %struct.Vec2*
  store %struct.Vec2* %18, %struct.Vec2** %19
  %20 = getelementptr inbounds [9 x i8], [9 x i8]* @.str.2, i32 0, i32 0
  %21 = call i32 @puts(i8* %20)
  %22 = load %struct.Vec2*, %struct.Vec2** %19
  call void @Vec2__print_vec(%struct.Vec2* %22)
  %23 = load %struct.Vec2*, %struct.Vec2** %19
  call void @Vec2__scale(%struct.Vec2* %23, float 0x4010000000000000)
  %24 = getelementptr inbounds [18 x i8], [18 x i8]* @.str.3, i32 0, i32 0
  %25 = call i32 @puts(i8* %24)
  %26 = load %struct.Vec2*, %struct.Vec2** %19
  call void @Vec2__print_vec(%struct.Vec2* %26)
  %27 = fneg float 0x3FF0000000000000
  %28 = load %struct.Vec2*, %struct.Vec2** %19
  call void @Vec2__translate(%struct.Vec2* %28, float 0x3FF0000000000000, float %27)
  %29 = getelementptr inbounds [17 x i8], [17 x i8]* @.str.4, i32 0, i32 0
  %30 = call i32 @puts(i8* %29)
  %31 = load %struct.Vec2*, %struct.Vec2** %19
  call void @Vec2__print_vec(%struct.Vec2* %31)
  ret i32 0
}


; String constants
@.fmtd = private unnamed_addr constant [4 x i8] c"%d\0A\00"
@.fmtf = private unnamed_addr constant [4 x i8] c"%f\0A\00"
@.str.0 = private unnamed_addr constant [3 x i8] c"x:\00"
@.str.1 = private unnamed_addr constant [3 x i8] c"y:\00"
@.str.2 = private unnamed_addr constant [9 x i8] c"Initial:\00"
@.str.3 = private unnamed_addr constant [18 x i8] c"After scale by 4:\00"
@.str.4 = private unnamed_addr constant [17 x i8] c"After translate:\00"
